---
op_api_role_enable: false
helm_op: false
ansible_op: false
go_op: false
op_cleanup: false
operator_sdk_version: "1.38.0"
op_api_dir: "/tmp/operator-api"
HELM_OP_IMAGE: "quay.io/{{quay_username}}/nginx-operator-helm:v1"
ANSIBLE_OP_IMAGE: "quay.io/{{quay_username}}/memcached-operator-ansible:v1"
GO_OP_IMAGE: "quay.io/{{quay_username}}/memcached-operator-go:v1"
quay_username: ""
quay_token: ""
docker_username: ""
docker_passwd: ""
